services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=secretsmanager,sqs,s3
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

  init-localstack:
    image: amazon/aws-cli
    depends_on:
      - localstack
    volumes:
      - "./create-secret.sh:/create-secret.sh"
    env_file:
      - .env
    entrypoint: [ "/bin/sh", "-c" ]
    command: ["yum install -y jq && /create-secret.sh"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M