spring:
  application:
    name: localstack
  cloud:
    aws:
      endpoint: http://localhost:4566
      sqs:
        queue:
          region: ${aws.region}
          auto-create: true
  config:
    import: aws-secretsmanager:/secret/localstack
